config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'social_media_profiles/sync_with_buffer'

  root 'home#index'

  # Campaigns
  resources :campaigns do
  end

  # Experiments
  resources :experiments, shallow: true do
    member do
      get 'parameterized_slug', to: 'experiments#parameterized_slug', constraints: lambda { |req| req.format == :json }
      get 'create_messages(.:format)', to: 'experiments#create_messages'
      get 'send_to_buffer', to: 'experiments#send_to_buffer'
      get 'correctness_analysis', to: 'experiments#correctness_analysis'
      get 'messages_page', to: 'experiments#messages_page'
      get 'comments_page', to: 'experiments#comments_page'
    end
    resources :message_generation_parameter_sets
  end

  # Clinical trials
  resources :clinical_trials do
  end

  # Message templates
  resources :message_templates do
    member do
      post 'get_image_selections', to: 'message_templates#get_image_selections', constraints: lambda { |req| req.format == :json }
      post 'add_image_to_image_pool', to: 'message_templates#add_image_to_image_pool', constraints: lambda { |req| req.format == :json }
      post 'remove_image_from_image_pool', to: 'message_templates#remove_image_from_image_pool', constraints: lambda { |req| req.format == :json }
    end
    collection do
      get :import
    end
  end

  # Messages
  resources :messages do
    collection do
      get :generate
    end
    member do
      post 'edit_campaign_id', to: 'messages#edit_campaign_id'
      get 'new_campaign_id', to: 'messages#new_campaign_id'
      post 'edit_note', to: 'messages#edit_note'
      get 'new_note', to: 'messages#new_note'
    end
  end

  # App settings
  namespace :admin do
  end

  # Images
  resources :images do
    collection do
      post :import
      get :check_validity_for_instagram_ads
      post :add
    end
    member do
      post 'edit_codes', to: 'images#edit_codes'
    end
  end
  
  #Comments
  resources :comments do
    member do
      post 'edit_codes', to: 'comments#edit_codes'
    end
  end

  # Analytics files
  resources :analytics_files do
    member do
      patch 'update', to: 'analytics_files#update', constraints: lambda { |req| req.format == :json }
    end
    collection do
      get 'process_all_files', to: 'analytics_files#process_all_files'
    end
  end

  # Social media profiles
  resources :social_media_profiles do
  end

  # Data dictionaries
  resources :data_dictionaries do
  end
  
  # Recommendations 
  get 'recommendations/', to: 'recommendations#get'
end

app/views/shared/_analytics_files.html.haml
- recent_analytics_files = analytics_files.select{ |analytics_file| analytics_file.required_upload_date >= Time.now - 2.days && analytics_file.required_upload_date <= Time.now + 1.day }.sort!{ |x, y| x.required_upload_date <=> y.required_upload_date }
%table.ui.celled.table
  %thead
    %tr
      %th
      %th Required upload date
      %th Social media type and username
      %th Medium
      %th
      %th Database Id
  %tbody
    - recent_analytics_files.each do |analytics_file|
      %tr{ class: [('positive' if !analytics_file.url.nil?)] }
        - if analytics_file.url.nil?
          %td
            %i.clock.icon
        - else
          %td
            %i.checkmark.box.icon
        %td= analytics_file.required_upload_date.strftime('%B %d, %Y')
        %td
          = analytics_file.social_media_profile.platform_icon_and_name 
          (#{analytics_file.social_media_profile.service_username})
        %td
          = analytics_file.social_media_profile.allowed_mediums[0].to_s.titleize
        - if analytics_file.url.nil?
          %td.collapsing
            %a.analytics-file-upload-button.ui.labeled.icon.button{'data-analytics-file-id': analytics_file.id, 'data-experiment-id': @experiment.id, 'data-experiment-param': @experiment.to_param}
              %i.upload.icon
              Upload analytics file
        - else
          %td
            %a.ui.labeled.icon.button{:href => "#{analytics_file.url}"}
              %i.download.icon
              Download
        %td
          = analytics_file.id.to_s
%h2.ui.header
  All analytics files
%table.ui.celled.table
  %thead
    %tr
      %th
      %th Required upload date
      %th Social media type and username
      %th Medium
      %th
      %th Database Id
  %tbody
    - analytics_files.to_a.sort!{ |x, y| x.required_upload_date <=> y.required_upload_date }.each do |analytics_file|
      %tr{ class: [('positive' if !analytics_file.url.nil?)] }
        - if analytics_file.url.nil?
          %td
            %i.clock.icon
        - else
          %td
            %i.checkmark.box.icon
        %td= analytics_file.required_upload_date.strftime('%B %d, %Y')
        %td
          = analytics_file.social_media_profile.platform_icon_and_name 
          (#{analytics_file.social_media_profile.service_username})
        %td
          = analytics_file.social_media_profile.allowed_mediums[0].to_s.titleize
        - if analytics_file.url.nil?
          %td.collapsing
        - else
          %td
            %a.ui.labeled.icon.button{:href => "#{analytics_file.url}"}
              %i.download.icon
              Download
        %td
          = analytics_file.id.to_s

app/views/shared/_campaigns.html.haml
%table.ui.celled.striped.table
  %thead 
    %tr
      %th Name
      %th Start date
      %th End date
      %th Access
  %tbody
    - @campaigns.each do |campaign|
      %tr
        %td= campaign.name
        %td
          - if !campaign.start_date.nil?
            = campaign.start_date.strftime('%B %d, %Y')
        %td
          - if !campaign.end_date.nil?
            = campaign.end_date.strftime('%B %d, %Y')
        %td
          %a{:href => campaign_path(campaign)}
            Show
          %a{:href => edit_campaign_path(campaign)}
            Edit

app/views/shared/_comments_page.html.haml
.ui.header
  .content
    = paginate comments, :remote => true
  .ui.right.floated.segment.object-count
    %h3.ui.header
      = page_entries_info comments
%table.ui.celled.striped.table
  %thead
    %tr
      %th.center.aligned Platform
      %th.center.aligned Message
      %th.center.aligned Message date
      %th.center.aligned Comment text
      %th.center.aligned Comment date
      %th.center.aligned Codes
      %th.center.aligned Toxicity score
  %tbody
    - comments.each do |comment|
      %tr
        %td.center.aligned
          = comment.message.social_media_profile.platform_icon_and_name('big')
        %td
          = comment.message.content
        %td
          - if comment.message.buffer_update 
            - if comment.message.buffer_update.sent_from_date_time
              = comment.message.buffer_update.sent_from_date_time.strftime("%m/%d/%Y")
            - else
              N/A
          - else
            = comment.message.scheduled_date_time.strftime("%m/%d/%Y")
        %td
          = comment.comment_text
        %td
          - if comment.comment_date
            = comment.comment_date.strftime("%m/%d/%Y")
          - else
            N/A
        %td
          - if current_user.role != :read_only
            = render partial: 'shared/forms/input_comment_codes.html.haml', locals: { experiment: @experiment, comment: comment }
        %td
          - if current_user.role != :read_only
            = comment.toxicity_score

app/views/shared/_experiments.html.haml
%table.ui.celled.striped.table
  %thead
    %tr
      %th Name
      %th Access
  %tbody
    - experiments.includes(:message_generation_parameter_set).each do |experiment|
      %tr
        %td= experiment.name
        %td
          %a.ui.basic.button{ href: "#{experiment_path(experiment)}#/setup" }
            Workspace
          %a.ui.basic.button{ href: "#{experiment_path(experiment)}#/dashboard" }
            Dashboard

app/views/shared/_image_pool.html.haml
%a.ui.labeled.basic.icon.button{ :href => "" }
  %i.eye.icon
  View all (#{image_pool.count})

app/views/shared/_message_campaign_id.html.haml
.ui.basic.label.edit-id{ 'data-message-id': message.id}
  %i.edit.icon
  Campaign Id:
  = message.campaign_id.to_s

app/views/shared/_message_comments.html.haml
= render partial: 'shared/comments', locals: { comments: comments, experiment_id: @experiment.id }

app/views/shared/_message_note.html.haml
.ui.basic.label.edit-note{ 'data-message-id': message.id}
  %i.edit.icon
  Note:
  = message.note

app/views/shared/_message_templates.haml
%table.ui.celled.padded.table
  %thead
    %tr
      %th
        Database ID
      %th
        ID (Assigned by Katja)
      %th
        Type
      %th
        Content
      %th
        Length
  %tbody
    - message_templates.each do |message_template|
      %tr
        %td= message_template.id.to_s
        %td= message_template.initial_id
        %td= message_template.message_type
        - if message_template.platform.start_with?('twitter') || message_template.platform.start_with?('facebook')
          %td= message_template.content
        - else
          %td
            %ul
              %li= message_template.content[0]
              %li http://clinicaltrials.keckmedicine.org/
              %li= message_template.content[1]
              %li= message_template.content[2]
              - if message_template.platform.start_with?('youtube')
                %li= message_template.content[3]
        - if message_template.platform.start_with?('twitter') || message_template.platform.start_with?('facebook')
          %td= message_template.content.length
        - else
          %td
            %ul
              %li= message_template.content[0].length
              %li= "http://clinicaltrials.keckmedicine.org/".length
              %li= message_template.content[1].length
              %li= message_template.content[2].length
              - if message_template.platform.start_with?('youtube')
                %li= message_template.content[3].length

app/views/shared/_messages.html.haml
.paginated-content#model{ 'data-experiment-id': experiment_id, 'data-model': 'messages' }
  = render partial: 'shared/messages_page', locals: { messages: messages, experiment_id: experiment_id }

app/views/shared/_messages_page.html.haml
.ui.header
  .content
    = paginate messages, :remote => true
  .ui.right.floated.segment.object-count
    %h3.ui.header
      = page_entries_info messages
  - grouped_messages = messages.group_by{ |message| message.scheduled_date_time.to_date }
  - grouped_messages.each do |scheduled_date, messages_by_scheduled_date|
    %h3.ui.dividing.header
      = scheduled_date.strftime("%b #{scheduled_date.day.ordinalize}")
    - grouped_messages_by_platform = messages_by_scheduled_date.group_by(&:platform)
    - grouped_messages_by_platform.each do |platform, messages_by_platform|
      %h4.ui.header
        %i{ :class => "#{platform.to_s} icon"}
        .content
          = platform.to_s.titleize
      .ui.items
        - messages_by_platform.each do |message|
          - show_label = false
          - if !message.buffer_update.nil? && !message.buffer_update.sent_from_date_time.nil?
            - if message.delayed?
              - show_label = true
          .item
            .ui.tiny.image
              -if message.image
                = image_tag "#{message.image.url}"
              -else
                = image_tag "no-image.png"
            .content
              = message.content
              - if show_label
                .ui.left.pointing.red.basic.label
                  The message was delayed
              .extra
                .ui.basic.small.label
                  %i.clock.outline.icon
                  #{message.scheduled_date_time.strftime("%I:%M %p")}
                .ui.basic.small.label
                  = message.medium.to_s.titleize
                .ui.basic.small.label
                  = message.social_media_profile.service_username
                .ui.basic.small.label
                  Database Id:
                  = message.id.to_s
                - if current_user.role != :read_only
                  - if message.edit_campaign_id?
                    = render partial: 'shared/forms/input_message_campaign_id.html.haml', locals: { message: message }
                  -elsif message.show_campaign_id?
                    = render partial: 'shared/message_campaign_id.html.haml', locals: { message: message }
                - if !message.buffer_update.nil?
                  - if !message.buffer_update.sent_from_date_time.nil?
                    .ui.basic.grey.small.label
                      %i.rocket.icon
                      Published from Buffer on #{message.social_media_profile.platform_icon_and_name} at #{message.buffer_update.sent_from_date_time.strftime("%I:%M %P, %b %d, %Y")}
                  - else
                    .ui.basic.grey.small.label
                      %i.rocket.icon
                      Sent to Buffer on #{message.buffer_update.created_at.strftime("%b %d, %Y")}
              - if message.click_meter_tracking_link
                .extra
                  .ui.small.basic.labels
                    .ui.url.label{ "data-content" => "#{message.click_meter_tracking_link.tracking_url}" }
                      %i.linkify.icon
                      Tracking URL
                    .ui.url.label{ "data-content" => "#{message.click_meter_tracking_link.destination_url}" }
                      %i.linkify.icon
                      Destination URL

app/views/shared/_post_templates.html.haml
- facebook_post_templates = @experiment.post_templates.select { |post_template| post_template.social_media_specification.platform == :facebook }
- google_post_templates = @experiment.post_templates.select { |post_template| post_template.social_media_specification.platform == :google }
- twitter_post_templates = @experiment.post_templates.select { |post_template| post_template.social_media_specification.platform == :twitter }
- if facebook_post_templates.count > 0
  %table.ui.celled.striped.table
    %thead
      %tr
        %th{ colspan: "7" } 
          %h3 Facebook Ad (News Feed)
      %tr
        %th Database ID
        %th Text
        %th Headline
        %th Link Description
        %th Call to Action
        %th Website URL
        %th Image pool
    %tbody
      - facebook_post_templates.each do |post_template|
        %tr
          %td= post_template.id
          %td= simple_format(post_template.content[:text])
          %td= post_template.content[:headline]
          %td= post_template.content[:link_description]
          %td= post_template.content[:call_to_action]
          %td= post_template.content[:website_url]
          %td= render partial: 'shared/image_pool', locals: { experiment: @experiment, image_pool: post_template.image_pool }
- if google_post_templates.count > 0
  %table.ui.celled.striped.table
    %thead
      %tr
        %th{ colspan: "7" } 
          %h3 Google Ad (Search Network)
      %tr
        %th Database ID
        %th Headline 1
        %th Headline 2
        %th Headline 3
        %th Description 1
        %th Description 2
        %th Website URL
    %tbody
      - google_post_templates.each do |post_template|
        %tr
          %td= post_template.id
          %td= post_template.content[:headline_1]
          %td= post_template.content[:headline_2]
          %td= post_template.content[:headline_3]
          %td= post_template.content[:description_1]
          %td= post_template.content[:description_2]
          %td= post_template.content[:website_url]
- if twitter_post_templates.count > 0
  %table.ui.celled.striped.table
    %thead
      %tr
        %th{ colspan: "7" } 
          %h3 Twitter Organic (Timeline)
      %tr
        %th Database ID
        %th Text
        %th Hashtags
        %th Website URL
        %th Image pool
    %tbody
      - twitter_post_templates.each do |post_template|
        %tr
          %td= post_template.id
          %td= post_template.content[:text]
          %td= post_template.content[:hashtags]
          %td= post_template.content[:website_url]
          %td= render partial: 'shared/image_pool', locals: { experiment: @experiment, image_pool: post_template.image_pool }

app/views/shared/_statistics.html.haml
- if message.message_template.platform.start_with?('twitter')
  %table.ui.celled.table.compact
    %thead
      %tr
        %th Data Source
        %th Retweets
        %th Favorites
        %th Mentions/Replies
        %th Clicks
        %th Potential
        %th Impressions
        %th User Profile Clicks
    %tbody
      - if !message.statistics.blank?
        %tr
          %td
            .ui.label Buffer
          %td
            = message.statistics['retweets']
          %td
            = message.statistics['favorites']
          %td
            = message.statistics['mentions']
          %td
            = message.statistics['clicks']
          %td
            = message.statistics['reach']
          %td
            N/A
          %td
            N/A
      - if !message.service_statistics.blank?
        %tr
          %td
            .ui.label Twitter
          %td
            = message.service_statistics['retweets']
          %td
            = message.service_statistics['favorites']
          %td
            = message.service_statistics['replies']
          %td
            = message.service_statistics['clicks']
          %td
            N/A
          %td
            = message.service_statistics['impressions']
          %td
            = message.service_statistics['user_profile_clicks']
- elsif message.message_template.platform.start_with?('facebook')
  - if !message.statistics.blank?
    .ui.horizontal.segments
      .ui.segment
        .ui.mini.horizontal.statistic
          .value
            = message.statistics['comments']
          .label
            Comments
      .ui.segment
        .ui.mini.horizontal.statistic
          .value
            = message.statistics['likes']
          .label
            Likes
      .ui.segment
        .ui.mini.horizontal.statistic
          .value
            = message.statistics['clicks']
          .label
            Clicks
      .ui.segment
        .ui.mini.horizontal.statistic
          .value
            = message.statistics['shares']
          .label
            Shares